Bettleproject/resultApp/urls.py
from django.contrib import admin
from django.urls import path
from resultApp import views

app_name = "resultApp"

urlpatterns = [
    path("gaming", views.gaming, name="gaming"),
    path("test", views.game_result, name="test")
]

Bettleproject/user/urls.py
from django.contrib import admin
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("login", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("home/<str:username>", views.home, name="home"),
    path("logout", views.logout, name="logout"),
    path("reload/", views.reload_bullet, name="reload")
]

FirstMe/FirstMe/urls.py
from django.contrib import admin
from django.urls import path
from mainApp import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # 홈페이지
    path('', views.home, name="home"),
    # #로그인 페이지
    path('registration/login/', views.login, name="login"),
    # 회원가입 페이지
    path('registration/signup/', views.signup, name="signup"),
    # 로그아웃
    path('registration/logout/', views.logout, name="logout"),
    # 내 명함 만들기 페이지 (1, 2로 나뉘어서 필수와 선택 보이게 할 것)
    path('make/', views.make, name="make"),
    # 내 명함 디테일 페이지
    path('mycard/<slug:card_link>/', views.detail, name="detail"),
    # 내 명함 수정 페이지
    path('mycard/<slug:card_link>/edit', views.edit, name="edit"),
    # 그룹 디테일
    path('group/<int:group_pk>/', views.group_detail, name="group_detail"),
    # 내 명함 1대1 초대 페이지
    path('<slug:card_link>/<int:access_code>/', views.personal_invitation, name="personal_invitation"),
    # 그룹 만들기 페이지(그룹 이름 입력하는 칸)
    path('make_group/', views.make_group, name="make_group"),
    # 그룹 초대 페이지
    path('group/<int:group_pk>/<int:access_code>/', views.group_invitation, name="group_invitation"),
   
    # 그룹 목록
    path('<slug:card_link>/group_list/', views.group_list, name="group_list"),
    # 친구 목록
    path('<slug:card_link>/friend_list/', views.friend_list, name="friend_list"),

]

Nabiya/Nabiya/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.start, name='start'),
    path('home', views.home, name='home'), # 첫 달력화면
    path('add_pet', views.add_pet, name='add_pet'),


    path('new_diary/<str:date>', views.new_diary, name='new_diary'),
    path('list_diary', views.list_diary, name='list_diary'),

    path('register/login', views.login, name='login'), 
    path('register/signup', views.signup, name='signup'), # 로그인 화면에서 가입하기 버튼 클릭 시 연결
    path('register/logout', views.logout, name='logout'),

    
    path('list_tag', views.list_tag, name='list_tag'),
    path('delete_tag/<int:tag_pk>', views.delete_tag, name='delete_tag'),

    path('add_todo/<str:date>', views.add_todo, name='add_todo'),
    path('delete_todo/<int:todo_pk>/<str:date>', views.delete_todo, name='delete_todo'),

    path('day_detail/<str:date>', views.day_detail, name='day_detail')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kudoc/kudoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # appMain
    path('', include('appMain.urls')),

    # allauth
    path('email_confirmation-done/',
    TemplateView.as_view(template_name="appAccount/email_confirmation_done.html"),
    name="account_email_confirmations_done"
    ),
    path('', include('allauth.urls')),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('registration/signup', views.signup, name="signup"),
    path('registration/login', views.login, name="login"),
    path('registration/logout', views.logout, name="logout"),
    path('pig_new', views.pig_new, name="pig_new"),
    path('pig_detail/<int:pig_pk>', views.pig_detail, name="pig_detail"),
    path('schedule_new/<int:pig_pk>', views.schedule_new, name="schedule_new"),
    path('pig_bye/<int:pig_pk>', views.pig_bye, name="pig_bye"),
    path('home/', views.landing, name="landing"),
    path('accounts/', include("allauth.urls")),
    path('bye_donate', views.bye_donate, name="bye_donate"),
    path('bye_winner', views.bye_winner, name="bye_winner"),
    path('bye_donate_complete', views.bye_donate_complete, name="bye_donate_complete"),
    path('bye_winner_complete', views.bye_winner_complete, name="bye_winner_complete"),
    path('arrive/<int:schedule_pk>', views.arrive, name='arrive'),
    path('addevent_complete', views.addevent_complete, name="addevent_complete"),
    path('addpig_complete', views.addpig_complete, name="addpig_complete"),
]

Bettleproject/bettleApp/models.py
from django.db import models
from django.contrib.auth.models import User
import json
# Create your models here.

class Team(models.Model):
    hostUser = models.ForeignKey(User, on_delete=models.CASCADE, related_name='hostUser', max_length=50)
    firstMember = models.CharField(max_length=200)
    secondMember = models.CharField(max_length=200)
    thirdMember = models.CharField(max_length=200)
    fourthMember = models.CharField(max_length=200)
    Tier = models.CharField(max_length=100)
    bulletBet = models.IntegerField(default=0)
    matchDates = models.CharField(max_length=500, null=True)

    def set_matchDates(self, date):
        self.matchDates = json.dumps(date)
        self.save()

    def get_matchDates(self):
        return json.loads(self.matchDates)

Bettleproject/bettleApp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required 
from .models import Team
# Create your views here.

@login_required(login_url="/user/login")
def teamadd(request): 
    if request.method == "POST":
        team = Team.objects.create(
            hostUser = request.user,
            firstMember = request.POST["firstMember"],
            secondMember = request.POST["secondMember"],
            thirdMember = request.POST["thirdMember"],
            fourthMember = request.POST["fourthMember"],
            Tier = request.POST["Tier"],
            bulletBet = request.POST["bulletBet"],
        )
        match_dates = request.POST.getlist('match_dates[]')
        team.set_matchDates(match_dates)
        print(request.POST["bulletBet"])
        print('날짜정보', team.get_matchDates())
        return redirect('teamlist')
    return render(request, 'teamadd.html')

@login_required(login_url="/user/login")
def teamlist(request):
    teams = Team.objects.all()
    return render(request, 'teamlist.html', {'teams' : teams})

def matchinfo(request,team_pk):
    info_team = Team.objects.get(pk=team_pk)
    return render(request, 'matchinfo.html', {'info_team' : info_team})

    

Bettleproject/bettleApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    {% block css %}
    {% endblock css %}
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300&family=Jua&display=swap" rel="stylesheet" />
    <title>BETTLE</title>
</head>
<body>
    </div>
    <nav class="nav_bar">
        <div class="nav_bar_logo">
            <img src="{% static 'logo.png' %}" />
        </div>
        
        <ul class="nav_bar_menu">
            <div class="menu_bar_item">
                <Li><a class="nav_bar_menuItem" href="{% url 'user:home' user.username %}"> HOME </a></Li>
                <Li><a class="nav_bar_menuItem" href="#"> BULLET 충전 </a></Li>
                <Li><a class="nav_bar_menuItem" href="{% url 'teamadd' %}"> 팀 생성하기 </a></Li>
                <Li><a class="nav_bar_menuItem" href="{% url 'teamlist' %}"> 팀 매칭하기 </a></Li>
                <Li><a class="nav_bar_menuItem" href="{% url 'user:logout' %}"> 로그아웃 </a></Li>

            </div>
        </ul>
    </nav>
    <div class = 'title'>
        {% block title %}
        {% endblock title %}
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

Bettleproject/bettleApp/templates/matchinfo 2.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'matchinfo.css' %}">
{% endblock css %}
{% block title %}
{% endblock title %}

{% block content %}
<h1>매칭된 팀의 정보를 확인하세요</h1>
<div class="info_box">
    <div>대표자는 소환사 {{info_team.hostUser}} 님</div>
    <div>
        <p>
        소환사 {{info_team.hostUser}} 님의 팀원들의 라이엇 아이디는<br>
        {{info_team.firstMember}}<br>
        {{info_team.secondMember}}<br>
        {{info_team.thirdMember}}<br>
        {{info_team.fourthMember}}<br>
        </p>
        <p>원하는 대전 시간은</p>
        {{info_team.matchDates}}
        <br>
        <p>이 팀이 배팅한 BULLET수는 {{}}개</p>
    </div>
    <a href="{% url 'startgame' %}">게임 시작하기</a>
</div>

{% endblock content %}

Bettleproject/bettleApp/templates/matchinfo.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'matchinfo.css' %}">
{% endblock css %}
{% block title %}
{% endblock title %}

{% block content %}
<div class="imgmatch">
    <img src="../../static/매칭된팀.png">
</div>
<br>
<br>
<br>
<div class="info_box">
    <div class="king">대표자ID : 소환사 {{info_team.hostUser}} 님</div>
    <div>
        <div><p>
        소환사 {{info_team.hostUser}} 님의 팀원들의 라이엇 아이디는<br>
        {{info_team.firstMember}}<br>
        {{info_team.secondMember}}<br>
        {{info_team.thirdMember}}<br>
        {{info_team.fourthMember}}<br>
        </p></div>
        <div><p>원하는 대전 시간은</p></div>
        {% for date in info_team.get_matchDates %}
        <p>{{ date }}</p>
        {% endfor %}
        <br>
        <div><p>이 팀이 배팅한 BULLET수는 {{info_team.bulletBet}}개</p></div>
        <a href="{% url 'resultApp:gaming' %}">GAME START!</a>
    </div>
</div>

{% endblock content %}

Bettleproject/bettleApp/templates/teamadd 2.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'teamadd.css' %}">
{% endblock %}


{% block title %}
<h1>팀 생성 페이지</h1>
{% endblock title %}

{% block content %}
<div class="teamadd_box">
    <form method="POST" action="" >
        {% csrf_token %}
        <div class="team_add">
            <p>대전에서 가장 중요한 건 우리의 팀!</p>
            <p>대전을 함께 할 팀원들을 입력해주세요<br>
                팀원들의 라이엇 아이디를 입력하고 제출 버튼을 눌러주세요</p>
            <div>
                <label for="hostUser">내 라이엇 아이디 : </label>
                <input type="text" name="hostUser" id="hostUser">
            </div>
            <div>
                <label for="firstMember">첫번째 소환사명 : </label>
                <input type="text" name="firstMember" id="firstMember">
            </div>
            <div>
                <label for="secondMember">두번째 소환사명: </label>
                <input type="text" name="secondMember" id="secondMember">
            </div>
            <div>
                <label for="thirdMember">세번째 소환사명: </label>
                <input type="text" name="thirdMember" id="thirdMember">
            </div>
            <div>
                <label for="thirdMember">네번째 소환사명: </label>
                <input type="text" name="fourthMember" id="fourthMember">
            </div>
        </div>
        <div class = 'team_option'>
            <div class = 'Tier_select'>
                <label for="Tier">팀 평균 티어를 골라주세요 : </label>
                <select name="Tier" id="Tier">
                    <option value = "bronze">브론즈</option>
                    <option value = "silver">실버</option>
                    <option value = "gold">골드</option>
                    <option value = "platium">플래티넘</option>
                    <option value = "diamond"`>다이아몬드</option>
                </select>
            </div>
            <div class = 'Day_select'>
                <label for="matchDate"> 원하는 매칭 시간대를 골라주세요 : </label>
                <div class="Monday">
                    <input type="checkbox" name="match_dates[]" value="월요일 낮(12:00~15:00)">
                    <input type="checkbox" name="match_dates[]" value="월요일 오후(15:00~18:00)">
                    <input type="checkbox" name="match_dates[]" value="월요일 저녁(18:00~21:00)">
                    <input type="checkbox" name="match_dates[]" value="월요일 밤(21:00~24:00)">
                    <input type="checkbox" name="match_dates[]" value="월요일 심야(24:00~03:00)">
                </div>
                <div class="Tuesday">
                    <input type="checkbox" name="match_dates[]" value="화요일 낮(12:00~15:00)">
                    <input type="checkbox" name="match_dates[]" value="화요일 오후(15:00~18:00)">
                    <input type="checkbox" name="match_dates[]" value="화요일 저녁(18:00~21:00)">
                    <input type="checkbox" name="match_dates[]" value="화요일 밤(21:00~24:00)">
                    <input type="checkbox" name="match_dates[]" value="화요일 심야(24:00~03:00)">
                </div>
                <div class="Wednesday">
                    <input type="checkbox" name="match_dates[]" value="수요일 낮(12:00~15:00)">
                    <input type="checkbox" name="match_dates[]" value="수요일 오후(15:00~18:00)">
                    <input type="checkbox" name="match_dates[]" value="수요일 저녁(18:00~21:00)">
                    <input type="checkbox" name="match_dates[]" value="수요일 밤(21:00~24:00)">
                    <input type="checkbox" name="match_dates[]" value="수요일 심야(24:00~03:00)">
                </div>
                <div class="Thursay">
                    <input type="checkbox" name="match_dates[]" value="목요일 낮(12:00~15:00)">
                    <input type="checkbox" name="match_dates[]" value="목요일 오후(15:00~18:00)">
                    <input type="checkbox" name="match_dates[]" value="목요일 저녁(18:00~21:00)">
                    <input type="checkbox" name="match_dates[]" value="목요일 밤(21:00~24:00)">
                    <input type="checkbox" name="match_dates[]" value="목요일 심야(24:00~03:00)">
                </div>
                <div class="Friday">
                    <input type="checkbox" name="match_dates[]" value="금요일 낮(12:00~15:00)">
                    <input type="checkbox" name="match_dates[]" value="금요일 오후(15:00~18:00)">
                    <input type="checkbox" name="match_dates[]" value="금요일 저녁(18:00~21:00)">
                    <input type="checkbox" name="match_dates[]" value="금요일 밤(21:00~24:00)">
                    <input type="checkbox" name="match_dates[]" value="금요일 심야(24:00~03:00)">
                </div>
                <div class="Saturday">
                    <input type="checkbox" name="match_dates[]" value="토요일 낮(12:00~15:00)">
                    <input type="checkbox" name="match_dates[]" value="토요일 오후(15:00~18:00)">
                    <input type="checkbox" name="match_dates[]" value="토요일 저녁(18:00~21:00)">
                    <input type="checkbox" name="match_dates[]" value="토요일 밤(21:00~24:00)">
                    <input type="checkbox" name="match_dates[]" value="토요일 심야(24:00~03:00)">
                </div>
                <div class="Sunday">
                    <input type="checkbox" name="match_dates[]" value="일요일 낮(12:00~15:00)">
                    <input type="checkbox" name="match_dates[]" value="일요일 오후(15:00~18:00)">
                    <input type="checkbox" name="match_dates[]" value="일요일 저녁(18:00~21:00)">
                    <input type="checkbox" name="match_dates[]" value="일요일 밤(21:00~24:00)">
                    <input type="checkbox" name="match_dates[]" value="일요일 심야(24:00~03:00)">
                </div>
            </div>
            <div class = 'bullet_Bet'>
                <label for="bulletBet">몇 개의 불릿을 배팅하시겠습니까?</label>
                <select name="bulletBet">
                    <option value = "bronze">5</option>
                    <option value = "silver">10</option>
                    <option value = "gold">15</option>
                    <option value = "platium">20</option>
                    <option value = "diamond">25</option>
                </select>
            </div>
            <button type="submit">팀 생성하기</button>
        </div>
    </form>
</div>
{% endblock content %}

Bettleproject/bettleApp/templates/teamadd.html
{% extends 'base.html' %} {% block css %} {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'teamadd.css' %}" />
{% endblock %} {% block title %} {% endblock title %} {% block content %}



<div class="teamadd_box">
    <div class="box1">
      <div class="title1">팀을 생성하세요</div>
    <form method="POST" action="">
      {% csrf_token %}
      <div class="team_add">
        <div class="ourteam">대전에서 가장 중요한 건 우리의 팀!</div>
        <div class="teammates">
          대전을 함께 할 팀원들을 입력해주세요<br />
          팀원들의 라이엇 아이디를 입력하고 제출 버튼을 눌러주세요
        </div>
        <div>
          <label for="hostUser"></label>
          <input class="user_input" type="text" name="hostUser" id="hostUser" placeholder="내 라이엇 아이디"/>
        </div>
        <div>
          <label for="firstMember"></label>
          <input class="user_input" type="text" name="firstMember" id="firstMember" placeholder="첫번째 소환사명:" />
        </div>
        <div>
          <label for="secondMember"></label>
          <input class="user_input" type="text" name="secondMember" id="secondMember" placeholder="두번째 소환사명:" />
        </div>
        <div>
          <label for="thirdMember"></label>
          <input class="user_input" type="text" name="thirdMember" id="thirdMember" placeholder="세번째 소환사명" />
        </div>
        <div>
          <label for="thirdMember"></label>
          <input class="user_input" type="text" name="fourthMember" id="fourthMember"placeholder="네번째 소환사명"/>
        </div>
      </div>
    </div>
      <div class="box2">
        <div class="title1">조건을 입력하세요</div>
        <br/>
        <div class="title2">팀원들의 평균 실력이 어떻게 되시나요?</div>
        <div class="Tier_select">
          <label for="Tier">팀 평균 티어를 골라주세요 : </label>
          <select name="Tier" id="Tier">
            <option value="bronze">브론즈</option>
            <option value="silver">실버</option>
            <option value="gold">골드</option>
            <option value="platium">플래티넘</option>
            <option value="diamond" `>다이아몬드</option>
          </select>
        </div>
        <div class="Day_select">
          <label for="matchDate"> 원하는 매칭 시간대를 골라주세요 : </label>
          <div class="Monday">
            <input
              type="checkbox"
              name="match_dates[]"
              value="월요일 낮(12:00~15:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="월요일 오후(15:00~18:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="월요일 저녁(18:00~21:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="월요일 밤(21:00~24:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="월요일 심야(24:00~03:00)"
            />
          </div>
          <div class="Tuesday">
            <input
              type="checkbox"
              name="match_dates[]"
              value="화요일 낮(12:00~15:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="화요일 오후(15:00~18:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="화요일 저녁(18:00~21:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="화요일 밤(21:00~24:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="화요일 심야(24:00~03:00)"
            />
          </div>
          <div class="Wednesday">
            <input
              type="checkbox"
              name="match_dates[]"
              value="수요일 낮(12:00~15:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="수요일 오후(15:00~18:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="수요일 저녁(18:00~21:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="수요일 밤(21:00~24:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="수요일 심야(24:00~03:00)"
            />
          </div>
          <div class="Thursay">
            <input
              type="checkbox"
              name="match_dates[]"
              value="목요일 낮(12:00~15:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="목요일 오후(15:00~18:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="목요일 저녁(18:00~21:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="목요일 밤(21:00~24:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="목요일 심야(24:00~03:00)"
            />
          </div>
          <div class="Friday">
            <input
              type="checkbox"
              name="match_dates[]"
              value="금요일 낮(12:00~15:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="금요일 오후(15:00~18:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="금요일 저녁(18:00~21:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="금요일 밤(21:00~24:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="금요일 심야(24:00~03:00)"
            />
          </div>
          <div class="Saturday">
            <input
              type="checkbox"
              name="match_dates[]"
              value="토요일 낮(12:00~15:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="토요일 오후(15:00~18:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="토요일 저녁(18:00~21:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="토요일 밤(21:00~24:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="토요일 심야(24:00~03:00)"
            />
          </div>
          <div class="Sunday">
            <input
              type="checkbox"
              name="match_dates[]"
              value="일요일 낮(12:00~15:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="일요일 오후(15:00~18:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="일요일 저녁(18:00~21:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="일요일 밤(21:00~24:00)"
            />
            <input
              type="checkbox"
              name="match_dates[]"
              value="일요일 심야(24:00~03:00)"
            />
          </div>
        </div>
        <div class="bullet_Bet">
          <label for="bulletBet">몇 개의 불릿을 배팅하시겠습니까?</label>
          <select name="bulletBet">
            <option value="5">5</option>
            <option value="10">10</option>
            <option value="15">15</option>
            <option value="20">20</option>
            <option value="25">25</option>
          </select>
        </div>
        <div class="maketeam">
            <button type="submit"> <img src="../../static/생성버튼.png" alt="export"></button>
        </div>       
      </div>
    </form>
  </div>
  <div class ="wave">
    <img src="../../static/배경 로고.png" alt="wave">
</div>
  {% endblock content %}
</div>

Bettleproject/bettleApp/templates/teamlist 2.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'teamlist.css' %}">
{% endblock css %}
{% block title %}
<h1>매칭할 팀을 찾아보세요</h1>
{% endblock title %}

{% block content %}
<h4>대전을 펼칠 팀을 찾아보세요</h4>
<p>오늘 나의 상대는 너다!
    <br>
    실시간으로 팀 매칭을 요청해 보세요
</p>
<div class="matching_box">
    {% if not teams %}
    <p>대기중인 팀이 없습니다.</p>
    {% endif %}
    {% for team in teams %}
        <div class = "team_wrapper">
            <div class = "team_hostuser">
                대표자는 <br>
                소환사 [{{team.hostUser}}]님 
                </div>
            <div class = "team_content">
                팀원들의 평균 실력은 <br>
                <p>{{team.Tier}}</p>
                <br>
                원하는 대전 시간은 <br>
                <p>{{team.matchDates}}</p>
                </div>
                <p>이 팀이 배팅한 BULLET 수는 {{team.bulletBet}}개</p>
                <a href="{% url 'matchinfo' team.pk %}">대전 요청</a>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock content %}

Bettleproject/bettleApp/templates/teamlist.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'teamlist.css' %}">
{% endblock css %}

{% block content %}
<div class="main">
    <div class="content1">
        대전을 펼칠 팀을 찾아보세요  
    </div>
    <div class="content2">
        오늘 나의 상대는 너다!
    </div>
    
        <br>
    실시간으로 팀 매칭을 요청해 보세요   
</div>
<div class="matching_box">
    {% if not teams %}
    <p>대기중인 팀이 없습니다.</p>
    {% endif %}
    <div class="team_container">
        {% for team in teams %}
            <div class = "team_wrapper">
                <div class = "team_hostuser">
                    대표자는 <br>
                    소환사 [{{team.hostUser}}]님 
                    </div>
                <div class = "team_content">
                    팀원들의 평균 실력은 <br>
                    <p>{{team.Tier}}</p>
                    <br>
                    원하는 대전 시간은 <br>
                    <p>{{team.get_matchDates}}</p>
                    </div>
                    <p>이 팀이 배팅한 BULLET 수는 {{team.bulletBet}}개</p>
                    <a href="{% url 'matchinfo' team.pk %}">대전 요청</a>
                </div>
                {% endfor %}
            </div>
    </div>
</div>

{% endblock content %}