Bettleproject/user/urls.py
from django.contrib import admin
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("login", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("home/<str:username>", views.home, name="home"),
    path("logout", views.logout, name="logout"),
    path("reload/", views.reload_bullet, name="reload")
]

FirstMe/FirstMe/urls.py
from django.contrib import admin
from django.urls import path
from mainApp import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # 홈페이지
    path('', views.home, name="home"),
    # #로그인 페이지
    path('registration/login/', views.login, name="login"),
    # 회원가입 페이지
    path('registration/signup/', views.signup, name="signup"),
    # 로그아웃
    path('registration/logout/', views.logout, name="logout"),
    # 내 명함 만들기 페이지 (1, 2로 나뉘어서 필수와 선택 보이게 할 것)
    path('make/', views.make, name="make"),
    # 내 명함 디테일 페이지
    path('mycard/<slug:card_link>/', views.detail, name="detail"),
    # 내 명함 수정 페이지
    path('mycard/<slug:card_link>/edit', views.edit, name="edit"),
    # 그룹 디테일
    path('group/<int:group_pk>/', views.group_detail, name="group_detail"),
    # 내 명함 1대1 초대 페이지
    path('<slug:card_link>/<int:access_code>/', views.personal_invitation, name="personal_invitation"),
    # 그룹 만들기 페이지(그룹 이름 입력하는 칸)
    path('make_group/', views.make_group, name="make_group"),
    # 그룹 초대 페이지
    path('group/<int:group_pk>/<int:access_code>/', views.group_invitation, name="group_invitation"),
   
    # 그룹 목록
    path('<slug:card_link>/group_list/', views.group_list, name="group_list"),
    # 친구 목록
    path('<slug:card_link>/friend_list/', views.friend_list, name="friend_list"),

]

Nabiya/Nabiya/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.start, name='start'),
    path('home', views.home, name='home'), # 첫 달력화면
    path('add_pet', views.add_pet, name='add_pet'),


    path('new_diary/<str:date>', views.new_diary, name='new_diary'),
    path('list_diary', views.list_diary, name='list_diary'),

    path('register/login', views.login, name='login'), 
    path('register/signup', views.signup, name='signup'), # 로그인 화면에서 가입하기 버튼 클릭 시 연결
    path('register/logout', views.logout, name='logout'),

    
    path('list_tag', views.list_tag, name='list_tag'),
    path('delete_tag/<int:tag_pk>', views.delete_tag, name='delete_tag'),

    path('add_todo/<str:date>', views.add_todo, name='add_todo'),
    path('delete_todo/<int:todo_pk>/<str:date>', views.delete_todo, name='delete_todo'),

    path('day_detail/<str:date>', views.day_detail, name='day_detail')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kudoc/kudoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # appMain
    path('', include('appMain.urls')),

    # allauth
    path('email_confirmation-done/',
    TemplateView.as_view(template_name="appAccount/email_confirmation_done.html"),
    name="account_email_confirmations_done"
    ),
    path('', include('allauth.urls')),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('registration/signup', views.signup, name="signup"),
    path('registration/login', views.login, name="login"),
    path('registration/logout', views.logout, name="logout"),
    path('pig_new', views.pig_new, name="pig_new"),
    path('pig_detail/<int:pig_pk>', views.pig_detail, name="pig_detail"),
    path('schedule_new/<int:pig_pk>', views.schedule_new, name="schedule_new"),
    path('pig_bye/<int:pig_pk>', views.pig_bye, name="pig_bye"),
    path('home/', views.landing, name="landing"),
    path('accounts/', include("allauth.urls")),
    path('bye_donate', views.bye_donate, name="bye_donate"),
    path('bye_winner', views.bye_winner, name="bye_winner"),
    path('bye_donate_complete', views.bye_donate_complete, name="bye_donate_complete"),
    path('bye_winner_complete', views.bye_winner_complete, name="bye_winner_complete"),
    path('arrive/<int:schedule_pk>', views.arrive, name='arrive'),
    path('addevent_complete', views.addevent_complete, name="addevent_complete"),
    path('addpig_complete', views.addpig_complete, name="addpig_complete"),
]

Bettleproject/user/models.py
from django.db import models
from django.contrib.auth.models import User

# from django.contrib.auth.models import AbstractUser
# # Create your models here.

class Bullet(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bullet")
    num = models.IntegerField(default=30)

    def __str__(self):
        return self.owner.username

Bettleproject/user/views.py
from tkinter import E
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from .riot_api import getSummonerInfo, getMatchsInfo, getOneMatchInfo
from .models import Bullet
from django.contrib.auth.decorators import login_required


DEVELOPMENTAPIKEY = "RGAPI-97f2ed81-4bee-4975-a55f-74510d188521"
# summonerName = "ㅂㄷㄱ"

# Create your views here.


def home(request, username):
    current_user = User.objects.get(username=username)
    bullet_num = Bullet.objects.get(owner__username=username)
    context = {"current_user": current_user, 'bullet_num':bullet_num.num}
    return render(request, "home.html", context)


def signup(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        password2 = request.POST["password2"]
        summoner_name = request.POST["summoner_name"]
        print(1)
        summoner_data = getSummonerInfo(DEVELOPMENTAPIKEY, summoner_name)
        print(2)
        summoner_nick = summoner_data["name"]
        summoner_encypted_id = summoner_data["id"]
        summoner_puuid = summoner_data["puuid"]
        if "status" in summoner_data:
            print(3)
            context = {"summoner_error_msg": "유효하지 않는 소환사명입니다."}
            return render(request, "signup.html", context)
        found_user = User.objects.filter(username=username)
        if password != password2:
            print(4)
            password_error_msg = "두 비밀번호가 일치하지 않습니다."
            return render(
                request,
                "signup.html",
                {"password_error_msg": password_error_msg, "username": username},
            )
        if len(found_user):
            print(5)
            error = "이미 아이디가 존재합니다"
            return render(request, "signup.html", {"error": error})
        new_user = User.objects.create_user(
            username=username,
            password=password,
            first_name=summoner_nick,
            last_name=summoner_puuid,
        )
        print(6)
        new_bullet = Bullet.objects.create(num=30, owner=new_user)
        auth.login(request, new_user)
        return redirect("user:home", username)
    return render(request, "signup.html")


def login(request):
    if request.method == "POST":
        print("g")
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect("user:home", username)
        error = "아이디 또는 비밀번호가 틀립니다."
        context = {"error": error}
        return render(request, "login.html", context)
    return render(request, "login.html")


def logout(request):
    auth.logout(request)
    return redirect("login")


# def validation(request):
#     matchs = getMatchsInfo(DEVELOPMENTAPIKEY, summoner_name)


@login_required(login_url="user/login/")
def reload_bullet(request):
    username = request.user.username
    bullet_now = Bullet.objects.get(owner__username=username)
    if request.method == "POST":
        bullet_reloaded = request.POST["bullet_reloaded"]
        num_reloaded = bullet_now.num + int(bullet_reloaded)
        Bullet.objects.update(num=num_reloaded)
        return redirect("user:home", username)
    context = {"username": username, "bullet_now": bullet_now}
    return render(request, "reload.html", context)

Bettleproject/user/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '../.css' %}">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300&family=Jua&display=swap" rel="stylesheet">
    <title>BETTLE</title>
</head>
<body>
  <div class="background">
    <nav class="nav_bar">
        <div class="nav_bar_logo">
          <img src="../../static/logo.png">
        </div>
        
        <ul class="nav_bar_menu">
          <div class="menu_bar_item">
            <Li><a class="nav_bar_menuItem" href="{% url 'user:home' user.username %}"> HOME </a></Li>
            <Li><a class="nav_bar_menuItem" href="{% url 'user:reload' %}"> BULLET 충전 </a></Li>
            <Li><a class="nav_bar_menuItem" href="{% url 'teamadd' %}"> 팀 생성하기 </a></Li>
            <Li><a class="nav_bar_menuItem" href="{% url 'teamlist' %}"> 팀 매칭하기 </a></Li>
            <Li><a class="nav_bar_menuItem" href="{% url 'user:logout' %}"> 로그아웃 </a></Li>

          </div>
      </ul>
    </nav>
<div class="container2">
    <div class ="container">
      <div class = 'title'>
        <h2> {{current_user.username}} 소환사님 환영합니다. </h2>
      </div>
    
      <div class="my_info">
        <p>내가 가진 불릿 수 : {{bullet_num}}개</p>
        <p>매칭된 팀 리스트</p>

        <div class="img">
          <a href="{% url 'teamlist' %}"><img src="../../static/매칭버튼.png"></a>
        </div>
      </div> 
    </div>
</div>
</body>

Bettleproject/user/templates/login 2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
 {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <div class="background">
      <div class="signup">
        <a href="{% url 'signup' %}"><img src="../../static/signup.png"></a>
      </div>

    <section class="login">
      <form action="" class="login_container" method="POST">
        {% csrf_token %} {% if error %}
        <p>{{error}}</p>
        {% endif %}
        <input type="text" name="username" placeholder="아이디" />
        <input type="password" name="password" placeholder="비밀번호" />
        <button type="submit"><img src="../../static/login.png"></button>
      </form>
      <!-- <img src="../static/login2.png" width="220" height="100" class="redimg"> -->
      
    </section>
  </body>
</html>

Bettleproject/user/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
 {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <div class="background">
      <div class="signup">
        <a href="{% url 'user:signup' %}"><img src="..\static\회원가입.png"></a>
      </div>

    <section class="login">
      <form action="" class="login_container" method="POST">
        {% csrf_token %} {% if error %}
        <p>{{error}}</p>
        {% endif %}
        <input type="text" name="username" placeholder="아이디" />
        <br>
        <input type="password" name="password" placeholder="비밀번호" />
        <br>
        <button type="submit">로그인하기</button>
      </form>
      
    </section>
  </body>
</html>

Bettleproject/user/templates/reload.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'reload.css' %}">
    <title>Document</title>
  </head>
  <body>
    <div class="reload">reload</div>
    <div class="usename">소환자명{{ username }}</div>
    <div class="bullet_now">
      현재 남은 Bullet은 다음과 같습니다.{{ bullet_now.num }}
    </div>

    <form method="POST">
      <select name="bullet_reloaded" id="bullet_reloaded">
        <option value="25">25</option>
        <option value="15">15</option>
        <option value="5">5</option>
      </select>

      <button type="submit">충전하기</button>
    </form>
  </body>
</html>

Bettleproject/user/templates/signup 2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>회원가입하기</title>
  </head>
  <body>
    <section id="signup">
      <form method="POST">
        {% csrf_token %}
        <input
          type="text"
          name="username"
          placeholder="아이디"
          value="{{ username }}"
        />
        <input type="text" name="summoner_name" placeholder="소환사명" />
        {% if summoner_error_msg %}
        <p style="color: red">{{ summoner_error_msg }}</p>
        {% endif %}
        <input type="password" name="password" placeholder="비밀번호" />
        {% if password_error_msg %}
        <p style="color: red">{{ password_error_msg }}</p>
        {% endif %}
        <input type="password" name="password2" placeholder="비밀번호 확인" />
        <button type="submit">회원가입하기</button>
      </form>
    </section>
  </body>
</html>

Bettleproject/user/templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'signup.css' %}" />
    <title>회원가입하기</title>
  </head>
  <body>
    <section>
      <form id="signup" method="POST">
        {% csrf_token %}
        <input class="label"
          type="text"
          name="username"
          placeholder="아이디"
          value="{{ username }}"
        />
        <input class="label" type="text" name="summoner_name" placeholder="소환사명" />
        {% if summoner_error_msg %}
        <p style="color: red">{{ summoner_error_msg }}</p>
        {% endif %}
        <input class="label" type="password" name="password" placeholder="비밀번호" />
        {% if password_error_msg %}
        <p style="color: red">{{ password_error_msg }}</p>
        {% endif %}
        <input class="label" type="password" name="password2" placeholder="비밀번호 확인" />
        <button type="submit">회원가입하기</button>
      </form>
    </section>
  </body>
</html>